name: vibestack_frontend
description: A modular Flutter frontend for VibeStack applications
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # HTTP Client
  dio: ^5.3.2
  dio_cache_interceptor: ^3.5.0
  
  # UI & Navigation
  go_router: ^12.1.3
  flutter_svg: ^2.0.9
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Utils
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Material 3
  google_fonts: ^6.1.0
  
  # I18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  import_sorter: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 