version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://vibestack:vibestack@db:5432/vibestack
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vibestack-network
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vibestack
      - POSTGRES_USER=vibestack
      - POSTGRES_PASSWORD=vibestack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vibestack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vibestack -d vibestack"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Adminer - Database GUI
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - vibestack-network
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  vibestack-network:
    driver: bridge 