[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "C90", "I", "N", "D", "UP", "B", "A", "C4", "T20", "Q"]
ignore = ["E501"]
exclude = [".venv", "__pycache__", "migrations"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--maxfail=1 --disable-warnings" 